package com.imie.tp.calculator.operation;

/**
 * @author Sarah
 *
 */
public class AdditionOperation extends OperationCommandBase {

    public float currentValue;

    public AdditionOperation(float baseValue) {
        super(baseValue);
        this.currentValue = baseValue;
    }

    /**
    *
    * Apply a value on parameter.
    * @param value to apply on currentValue.
    */
    @Override
    public void make(float value) {
        this.currentValue = this.currentValue + value;

    }

    /**
    *
    * Get the current value generated by the make function.
    * @return the current value.
    */
    public float getCurrentValue() {
        return this.currentValue;
    }
}
