package com.imie.tp.calculator.operation;

/**
 * @author Sarah
 *
 */
public class AdditionOperation extends OperationCommandBase {

    /**
    *
    * Initial value
    */
    private float currentValue = 0;

    /**
    *
    * Constructor with initial value.
    * @param baseValue as an initial value.
    */
    public AdditionOperation(final float baseValue) {
        super(baseValue);
        this.currentValue = baseValue;
    }

    /**
    *
    * Apply a value on parameter.
    * @param value to apply on currentValue.
    */
    @Override
    public final void make(final float value) {
        this.currentValue = this.currentValue + value;

    }

    /**
    *
    * Get the current value generated by the make function.
    * @return the current value.
    */
    public final float getCurrentValue() {
        return this.currentValue;
    }
}
